
default: &default
  #adapter   : postgresql
  #pool      : 5
  #timeout   : 5000
  #user      : postgres  
  #password  : postgres
  #host      : localhost

  adapter    : mysql2
  encoding   : utf8
  username   : root
  password   : tvsnext
  host       : localhost

development:
  <<: *default
  database: pm_development

test:
  <<: *default
  database: pm_test

production:
  <<: *default
  database: pm_production