
default: &default
  adapter   : postgresql
  pool      : 5
  timeout   : 5000
  user      : yogesh  
  password  : bliss
  host      : localhost

development:
  <<: *default
  database: pm_development

test:
  <<: *default
  database: pm_test

production:
  <<: *default
  database: pm_production