
default: &default
  adapter   : postgresql
  pool      : 5
  timeout   : 5000
  user      : yogesh
  password  : bliss
  host      : localhost

development:
  <<: *default
  database: bliss_pm_development

test:
  <<: *default
  database: bliss_pm_test

production:
  <<: *default
  database: bliss_pm_production